# Generated by Django 4.2.8 on 2024-01-05 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('cooking_time', models.IntegerField()),
                ('ingredients', models.CharField(max_length=350)),
                ('description', models.TextField()),
            ],
        ),
    ]
