# Generated by Django 5.0.1 on 2024-01-29 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_pic'),
    ]

    operations = [
    ]
